### ISSUE TITLE
The Crystal lib can only be linked to a specific version of ICU

### ISSUE THREAD

**Issue by olbat** [olbat/icu.cr#1]
For some reasons <sup>[1](https://bugs.launchpad.net/ubuntu/+source/icu/+bug/675946),[2](https://sourceforge.net/p/icu/mailman/message/19575338/),[3](http://userguide.icu-project.org/design#TOC-ICU-Binary-Compatibility:-Using-ICU-as-an-Operating-System-Level-Library)</sup>, most distributions of ICU are compiled using the symbol renaming feature ([a suffix](https://pastebin.com/ZGvqNcAt) containing the ICU version number is added to every symbols in shared objects).

It makes the task of creating a generic Crystal binding more difficult since ABIs of different versions of ICU are 100% incompatible.

For the moment the [lib_icu](https://github.com/olbat/icu.cr/blob/master/src/lib_icu/) binding has been [generated](https://github.com/olbat/libgen) against the version 52 of ICU making it incompatible with any other version of the library.

**Comment by olbat** [comment]
Here are some ideas to solve the issue:
1. Use a [linker script](https://stackoverflow.com/questions/41934005/rename-a-symbol-using-a-linker-script) to rename symbols at linking time
2. Generate<sup>[1](https://github.com/olbat/libgen),[2](https://github.com/olbat/icu.cr/blob/master/lib.yml)</sup> the binding at install time (via [postinstall script](https://github.com/crystal-lang/shards/blob/master/SPEC.md#postinstall) in the shard ?)
3. Generate bindings for the N last versions of ICU (+ a binding without suffixes )
  and choose which one to load at compile time
4. Distribute a version of ICU sources with the library + compile it before the Crystal library
5. Wait for some "[on-the-fly code generation](https://github.com/crystal-lang/crystal/pull/2442)" feature to be integrated in Crystal core

**Comment by olbat** [comment]
This topic is also discussed on [Crystal's google group](https://groups.google.com/d/topic/crystal-lang/sD4EXgDQWFQ/discussion).

__update__: see https://gist.github.com/olbat/4a5d6d474efd54e14fbac317b3ae8819

**Comment by kostya** [comment]
there is also different so names for osx and linux, i write little binding here: https://github.com/kostya/icu/blob/master/src/icu/lib.cr, but it not solve suffixes
