### ISSUE TITLE
macOS compatibility

### ISSUE THREAD

**Issue by olbat** [olbat/icu.cr#2]
For the moment the binding does not seems to work on macOS (cf. [CI's logs](https://travis-ci.org/olbat/icu.cr/jobs/228797242)).

**Comment by kostya** [comment]
on osx i get this:
```
Plugins are disabled.
Plugins are disabled.
U_ILLEGAL_ARGUMENT_ERROR (ICU::Error)
0x1000f2295: *CallStack::unwind:Array(Pointer(Void)) at ??
0x1000f2231: *CallStack#initialize:Array(Pointer(Void)) at ??
0x1000f2208: *CallStack::new:CallStack at ??
0x1000f13a1: *raise<ICU::Error>:NoReturn at ??
0x100121e00: *ICU::check_error!<LibICU::UErrorCode>:Nil at ??
0x100121d05: *ICU::CharsetDetector#initialize:Nil at ??
0x100121cc1: *ICU::CharsetDetector::new:ICU::CharsetDetector at ??
0x1000eb7f1: __crystal_main at ??
0x1000f1238: main at ??
```

**Comment by olbat** [comment]
For the record, here is [a link](http://userguide.icu-project.org/dev/codingguidelines#TOC-Details-about-ICU-Error-Codes) to the doc that explains how errors should be handled (the status variable should be reseted to UZeroError before each call just as you did).

So I think that in the end, this issue was not linked to macOS at all ... it's version was just more recent than any other I tested that's why there was this error (plus the fact that warnings were handled as errors).
